// Code generated by go generate ./api; DO NOT EDIT.

package api

type Operation struct {
	Method string
	Path   string
	ID     string
}

const OpenAPIVersion = "3.1.0"
const OpenAPISHA256 = "ed3679710a96991d2f1e42503b3cbbc7dd94d0725071e95f3011242d8e967024"

var Operations = []Operation{
	{Method: "GET", Path: "/api/openapi.json", ID: "getOpenAPI"},
	{Method: "POST", Path: "/api/v1/auth/login", ID: "loginLocal"},
	{Method: "POST", Path: "/api/v1/auth/logout", ID: "logoutLocal"},
	{Method: "GET", Path: "/api/v1/sessions", ID: "listSessions"},
	{Method: "DELETE", Path: "/api/v1/sessions/{sessionId}", ID: "revokeSession"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/export", ID: "exportWorkspace"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/import", ID: "importWorkspace"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/invitations", ID: "listInvitations"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/invitations", ID: "createInvitation"},
	{Method: "DELETE", Path: "/api/v1/workspaces/{workspaceId}/invitations/{invitationId}", ID: "revokeInvitation"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/invitations/{invitationId}/resend", ID: "resendInvitation"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/items", ID: "listItems"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/items", ID: "createItem"},
	{Method: "DELETE", Path: "/api/v1/workspaces/{workspaceId}/items/{itemId}", ID: "deleteItem"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/items/{itemId}", ID: "getItem"},
	{Method: "PATCH", Path: "/api/v1/workspaces/{workspaceId}/items/{itemId}", ID: "updateItem"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/members", ID: "listMembers"},
	{Method: "DELETE", Path: "/api/v1/workspaces/{workspaceId}/members/{userId}", ID: "removeMember"},
	{Method: "PATCH", Path: "/api/v1/workspaces/{workspaceId}/members/{userId}", ID: "changeMemberRole"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/ownership", ID: "transferOwnership"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/tokens", ID: "listTokens"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/tokens", ID: "createToken"},
	{Method: "DELETE", Path: "/api/v1/workspaces/{workspaceId}/tokens/{tokenId}", ID: "revokeToken"},
	{Method: "PATCH", Path: "/api/v1/workspaces/{workspaceId}/tokens/{tokenId}", ID: "updateToken"},
	{Method: "GET", Path: "/health/live", ID: "getLiveness"},
	{Method: "GET", Path: "/health/ready", ID: "getReadiness"},
}
