// Code generated by go generate ./api; DO NOT EDIT.

package api

type Operation struct {
	Method string
	Path   string
	ID     string
}

const OpenAPIVersion = "3.1.0"
const OpenAPISHA256 = "74ff652f982898273d7606faaa3e3d2e93f72f94093090ef63286b395e3a3173"

var Operations = []Operation{
	{Method: "GET", Path: "/api/openapi.json", ID: "getOpenAPI"},
	{Method: "POST", Path: "/api/v1/auth/login", ID: "loginLocal"},
	{Method: "POST", Path: "/api/v1/auth/logout", ID: "logoutLocal"},
	{Method: "POST", Path: "/api/v1/auth/mfa/passkey", ID: "mfaLoginPasskey"},
	{Method: "POST", Path: "/api/v1/auth/mfa/passkeys/register", ID: "mfaPasskeyComplete"},
	{Method: "POST", Path: "/api/v1/auth/mfa/passkeys/register/options", ID: "mfaPasskeyOptions"},
	{Method: "DELETE", Path: "/api/v1/auth/mfa/passkeys/{passkeyId}", ID: "mfaPasskeyRemove"},
	{Method: "POST", Path: "/api/v1/auth/mfa/recovery", ID: "mfaLoginRecovery"},
	{Method: "GET", Path: "/api/v1/auth/mfa/status", ID: "mfaStatus"},
	{Method: "DELETE", Path: "/api/v1/auth/mfa/totp", ID: "mfaTotpRemove"},
	{Method: "POST", Path: "/api/v1/auth/mfa/totp", ID: "mfaLoginTOTP"},
	{Method: "POST", Path: "/api/v1/auth/mfa/totp/complete", ID: "mfaTotpComplete"},
	{Method: "POST", Path: "/api/v1/auth/mfa/totp/enroll", ID: "mfaTotpEnroll"},
	{Method: "GET", Path: "/api/v1/sessions", ID: "listSessions"},
	{Method: "DELETE", Path: "/api/v1/sessions/{sessionId}", ID: "revokeSession"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/export", ID: "exportWorkspace"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/import", ID: "importWorkspace"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/invitations", ID: "listInvitations"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/invitations", ID: "createInvitation"},
	{Method: "DELETE", Path: "/api/v1/workspaces/{workspaceId}/invitations/{invitationId}", ID: "revokeInvitation"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/invitations/{invitationId}/resend", ID: "resendInvitation"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/items", ID: "listItems"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/items", ID: "createItem"},
	{Method: "DELETE", Path: "/api/v1/workspaces/{workspaceId}/items/{itemId}", ID: "deleteItem"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/items/{itemId}", ID: "getItem"},
	{Method: "PATCH", Path: "/api/v1/workspaces/{workspaceId}/items/{itemId}", ID: "updateItem"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/members", ID: "listMembers"},
	{Method: "DELETE", Path: "/api/v1/workspaces/{workspaceId}/members/{userId}", ID: "removeMember"},
	{Method: "PATCH", Path: "/api/v1/workspaces/{workspaceId}/members/{userId}", ID: "changeMemberRole"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/ownership", ID: "transferOwnership"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/tokens", ID: "listTokens"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/tokens", ID: "createToken"},
	{Method: "DELETE", Path: "/api/v1/workspaces/{workspaceId}/tokens/{tokenId}", ID: "revokeToken"},
	{Method: "PATCH", Path: "/api/v1/workspaces/{workspaceId}/tokens/{tokenId}", ID: "updateToken"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/webhooks", ID: "listWebhooks"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/webhooks", ID: "createWebhook"},
	{Method: "DELETE", Path: "/api/v1/workspaces/{workspaceId}/webhooks/{webhookId}", ID: "deleteWebhook"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/webhooks/{webhookId}/deliveries", ID: "listWebhookDeliveries"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/webhooks/{webhookId}/secret", ID: "rotateWebhookSecret"},
	{Method: "GET", Path: "/health/live", ID: "getLiveness"},
	{Method: "GET", Path: "/health/ready", ID: "getReadiness"},
}
