// Code generated by go generate ./api; DO NOT EDIT.

package api

type Operation struct {
	Method string
	Path   string
	ID     string
}

const OpenAPIVersion = "3.1.0"
const OpenAPISHA256 = "49c3f28659bb984daf3c2ada1645c66aba4fc05dcb364b95b1f3585a2031f12b"

var Operations = []Operation{
	{Method: "GET", Path: "/api/openapi.json", ID: "getOpenAPI"},
	{Method: "POST", Path: "/api/v1/auth/login", ID: "loginLocal"},
	{Method: "POST", Path: "/api/v1/auth/logout", ID: "logoutLocal"},
	{Method: "GET", Path: "/api/v1/sessions", ID: "listSessions"},
	{Method: "DELETE", Path: "/api/v1/sessions/{sessionId}", ID: "revokeSession"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/export", ID: "exportWorkspace"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/files", ID: "listFiles"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/files", ID: "createFile"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/files/uploads", ID: "initiateFileUpload"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/files/{fileId}", ID: "getFile"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/files/{fileId}/complete", ID: "completeFileUpload"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/files/{fileId}/content", ID: "getFileContent"},
	{Method: "PUT", Path: "/api/v1/workspaces/{workspaceId}/files/{fileId}/content", ID: "uploadFileContent"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/import", ID: "importWorkspace"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/invitations", ID: "listInvitations"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/invitations", ID: "createInvitation"},
	{Method: "DELETE", Path: "/api/v1/workspaces/{workspaceId}/invitations/{invitationId}", ID: "revokeInvitation"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/invitations/{invitationId}/resend", ID: "resendInvitation"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/items", ID: "listItems"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/items", ID: "createItem"},
	{Method: "DELETE", Path: "/api/v1/workspaces/{workspaceId}/items/{itemId}", ID: "deleteItem"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/items/{itemId}", ID: "getItem"},
	{Method: "PATCH", Path: "/api/v1/workspaces/{workspaceId}/items/{itemId}", ID: "updateItem"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/members", ID: "listMembers"},
	{Method: "DELETE", Path: "/api/v1/workspaces/{workspaceId}/members/{userId}", ID: "removeMember"},
	{Method: "PATCH", Path: "/api/v1/workspaces/{workspaceId}/members/{userId}", ID: "changeMemberRole"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/ownership", ID: "transferOwnership"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/tokens", ID: "listTokens"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/tokens", ID: "createToken"},
	{Method: "DELETE", Path: "/api/v1/workspaces/{workspaceId}/tokens/{tokenId}", ID: "revokeToken"},
	{Method: "PATCH", Path: "/api/v1/workspaces/{workspaceId}/tokens/{tokenId}", ID: "updateToken"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/webhooks", ID: "listWebhooks"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/webhooks", ID: "createWebhook"},
	{Method: "DELETE", Path: "/api/v1/workspaces/{workspaceId}/webhooks/{webhookId}", ID: "deleteWebhook"},
	{Method: "GET", Path: "/api/v1/workspaces/{workspaceId}/webhooks/{webhookId}/deliveries", ID: "listWebhookDeliveries"},
	{Method: "POST", Path: "/api/v1/workspaces/{workspaceId}/webhooks/{webhookId}/secret", ID: "rotateWebhookSecret"},
	{Method: "GET", Path: "/health/live", ID: "getLiveness"},
	{Method: "GET", Path: "/health/ready", ID: "getReadiness"},
}
